### PR TITLE
ITiCSE study materials for class-exp and dclass-exp

### PR DESCRIPTION
**Pull request by barbarer**
This is to allow ITiCSE study members who already use Runestone ebooks to run the class-exp and dclass-exp studies in their usual ebook

### CODE REVIEW

**Comment by bnmnetp** [comment]
Some of this looks like multiple choice questions, but some of this looks like content???  I thought you were just adding files with questions.

**Comment by barbarer** [comment]
This is a study for the ITiCSE working group.  It has several parts.  It
won't be visible in the ebook table of contents.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by bnmnetp** [comment]
Sorry  if I am being dense, but aren't these questions already in the database?  So they can already search for them to add to their assignments?

**Comment by barbarer** [comment]
Hi Brad,

The questions are part of a study and we need all the study materials.  Is
there a problem with just adding the same question to multiple ebooks?

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by bnmnetp** [comment]
There is not a problem with adding the same question, to multiple books but it is not necessary when you can search for questions across books.

Why we are dumping a pile of new files into a book, but we are not adding anything to the toctree?  That creates tons of warnings and confusion about why things are there.  Then it gets more confusing because it appears that some of the content duplicates what is already there.

You have said this is part of a study, and this is content that is from one of the books created for the study.  What problem are we solving?  Or are we creating a bigger problem?

**Comment by barbarer** [comment]
We are solving the problem that we want to run the study with both people
who don't normally use Runestone as well as people who do.  Jan and Susan
plan on running some of our studies and already use the thinkcspy ebook.
They don't want to have to have their students add another ebook.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by bnmnetp** [comment]
Could we at least put it in its own chapter maybe marked as part of the experiment?  We could link it to the TOC as an appendix or something?

**Comment by bnmnetp** [comment]
That would make it a lot less confusing than having it mixed into the ClassesBasics chapter.

**Comment by barbarer** [comment]
I moved the files into a folder called experiments

**Comment by pearcej** [comment]
@bnmnetp @barbarer I have been following this discussion with interest because  I am planning to run studies using a different book as well. I think that moving these experiments into a specially named folder is a reasonable solution. 

Even so, I agree that throwing unexplained warnings is not great since many people build Runestone books. I wonder if storing them in a specially named folder that clues the build not to throw errors would be an improvement.  For example, what if we decided we would always use a folder named experiment or perhaps something like _experiments as a folder name? It should be easy to then never throw warnings on such files not being in the toctree. Furthermore, a folder that begins with an underscore is very unlikely to be a folder that an author would be using for organizational purposes.

Thoughts?

**Comment by barbarer** [comment]
Sounds like a good solution to me.  I also like to add assignments to the
ebook that are not visible in the ebook so maybe a not_visible folder?

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Pull request merged**
