### PR TITLE
update pretext version and refresh some files

### PR DESCRIPTION
**Pull request by StevenClontz**
Oscar and I are working with John Cigas and this PR reflects any tweaks I would suggest.

### CODE REVIEW

**Comment by StevenClontz** [comment]
I doubt this will fix all the problems, but maybe this gets things moving in the right direction.

**Comment by bnmnetp** [comment]
Wow!  You all had a very productive dropin today!

**Comment by cigas** [comment]
Found the (first!) real problem. It was from adding `<introduction>` divisions around `<exercise>`
from Eliminate Warnings on Build #253

**Comment by StevenClontz** [comment]
Ah ha. Yup, introduction isn't as permissive as other content areas.

**Comment by StevenClontz** [comment]
Something that surprises me here: @oscarlevin's pretext-tools plugin doesn't fire any warnings when I look at 
image
in Codespaces. Is this my user error or a bug?

**Comment by oscarlevin** [comment]
What sort of warnings are you expecting?

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by StevenClontz** [comment]
Maybe I'm confused on the issue. Is an exercise allowed by the schema in the introduction of a section? https://pretextbook.org/doc/schema/schemas/pretext_xsd/elements/introduction.html seems to suggest that's okay.

**Comment by oscarlevin** [comment]
Ah, I didn't notice that.  I'm not sure what the current status of numbered elements in an introduction is.  It is possible that the schema still says that is okay, but Rob wants to change it.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
