### PR TITLE
Changed wording in question to clarify the definition of a leap year in Exercises.rst

### PR DESCRIPTION
**Pull request by gardhi01**

### CODE REVIEW

**Comment by bnmnetp** [comment]
I'm assuming that you have rebuilt the book and tested the links, but I just wanted to check before I accept this PR.

**Comment by gardhi01** [comment]
Yes, I rebuilt the book and tested the links in the GUIandEventDrivenProgramming chapter. Everything worked.

**Comment by bnmnetp** [comment]
OK, great.  I'll accept the PR then.

**Comment by bnmnetp** [comment]
@gardhi01 To make it easy to track, could you please mention the issue numbers when you submit a pull request that fixes one or more issues.  Thanks  using #number will give us a link.

**Pull request merged**
